---
version: '3.3'
services:
        cocktails:
                image: cocktailsgui:latest
                build: .
                ports: ["80:5000"]
                volumes: ["./src/config.json:/app/config.json"]
                restart: unless-stopped
