---
version: '3.3'
services:
        cocktails:
                image: cocktail_menu:latest
                build: .
                ports: ["8997:5000"]
                volumes: ["./src/config.json:/app/config.json"]
                restart: unless-stopped
